spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: false

  liquibase:
    change-log: classpath:db-migrations/changelog/changelog-master.xml

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR